update

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -54,6 +54,14 @@ runs:
           fi
           AWS_ACTION="revoke-security-group-ingress"
           MSG="Rule does not exist ..."
+        elif [ "$ACTION" == "describe" ]; then
+          aws ec2 describe-security-group-rules --filter Name="group-id",Values="$SG_ID" | jq ".[] | .[] | select(.CidrIpv4==\"$THIS_IP/32\")"
+        else
+          echo "ERROR: Wrong action defined"
+          echo "Supported actions are:"
+          echo "\t authorize"
+          echo "\t revoke"
+          exit 1
         fi
         if [ $EXECUTE == true ]; then
           aws ec2 $AWS_ACTION --group-id $SG_ID --ip-permissions IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges="[{CidrIp=$THIS_IP/32,Description=\"Created by Github Action.\"}]"
